#!/usr/bin/env bash
# Measure pixel dimensions of every image in public/experimental and emit a
# generated TS lookup at src/lib/experimental/dimensions.ts.
# Re-run whenever experimental image assets change (e.g. after sync-experimental-assets.sh).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/public/experimental"
OUT="$ROOT/src/lib/experimental/dimensions.ts"

{
  echo "// AUTO-GENERATED by scripts/measure-experimental-dimensions.sh — do not edit by hand."
  echo "// Maps each experimental media src to its intrinsic pixel size so <img>/<video>"
  echo "// can reserve layout space (prevents CLS)."
  echo ""
  echo "export type MediaSize = { width: number; height: number };"
  echo ""
  echo "export const MEDIA_DIMENSIONS: Record<string, MediaSize> = {"
  while IFS= read -r f; do
    dims=$(sips -g pixelWidth -g pixelHeight "$f" 2>/dev/null \
      | awk '/pixelWidth/{w=$2}/pixelHeight/{h=$2}END{print w" "h}')
    w=${dims% *}
    h=${dims#* }
    [[ -z "$w" || -z "$h" ]] && continue
    rel="/experimental/${f#"$SRC"/}"
    echo "  \"$rel\": { width: $w, height: $h },"
  done < <(find "$SRC" -type f \( -name '*.jpg' -o -name '*.png' -o -name '*.gif' \) | sort)
  echo "};"
  echo ""
  echo "export function getMediaSize(src: string): MediaSize | undefined {"
  echo "  return MEDIA_DIMENSIONS[src];"
  echo "}"
} > "$OUT"

echo "Wrote $OUT"
